name: ChatHub
options:
     deploymentTarget:
         iOS: 14.0
     bundleIdPrefix: com.jakubmalczyk
targets:
    ChatHub:
     type: application
     platform: iOS
     sources:
     - path: ChatHub
     dependencies:
     - package: Firebase
packages:
    Firebase:
        url: https://github.com/firebase/firebase-ios-sdk.git
        branch: master
