name: ChatHub
include:
- GoogleService-Info.plist
options:
     deploymentTarget:
         iOS: 14.0
     bundleIdPrefix: com.jakubmalczyk
targets:
    ChatHub:
     type: application
     platform: iOS
     sources:
     - path: ChatHub
     dependencies:
     - package: FirebaseAuth
     - package: FirebaseFirestoreSwift
     - package: FirebaseFunctions
     - package: FirebaseStorage
     - package: Kingfisher
     - package: Swinject
packages:
    FirebaseAuth:
        url: https://github.com/firebase/firebase-ios-sdk.git
        branch: master
    FirebaseFirestoreSwift:
        url: https://github.com/firebase/firebase-ios-sdk.git
        branch: master
    FirebaseFunctions:
        url: https://github.com/firebase/firebase-ios-sdk.git
        branch: master
    FirebaseStorage:
        url: https://github.com/firebase/firebase-ios-sdk.git
        branch: master
    Kingfisher:
        url: https://github.com/onevcat/Kingfisher.git
        branch: master
    Swinject:
        url: https://github.com/Swinject/Swinject.git
        branch: master
